import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Candidate } from '../../entities/candidate.entity';
import { CountySeed } from './county.seed';
import { ConstituencySeed } from './constituency.seed';
import { WardSeed } from './ward.seed';
import { ElectionSeed } from './election.seed';

interface CandidateData {
  candidateNumber: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  position: string;
  countyCode?: string;
  constituencyCode?: string;
  wardCode?: string;
  partyName: string;
  partyAbbreviation: string;
  isIndependent: boolean;
  dateOfBirth: Date;
  electionId?: string;
}

@Injectable()
export class CandidateSeed {
  private readonly logger = new Logger(CandidateSeed.name);

  // Kenyan political parties
  private readonly parties = [
    { name: 'Jubilee Party', abbreviation: 'JP' },
    { name: 'Orange Democratic Movement', abbreviation: 'ODM' },
    { name: 'Kenya African National Union', abbreviation: 'KANU' },
    { name: 'Wiper Democratic Movement', abbreviation: 'WDM' },
    { name: ' Amani National Congress', abbreviation: 'ANC' },
    { name: 'Ford Kenya', abbreviation: 'FORD-K' },
    { name: 'Kenya Union Party', abbreviation: 'KUP' },
    { name: 'Chama Cha Mashinani', abbreviation: 'CCM' },
    { name: 'National Rainbow Coalition', abbreviation: 'NARC' },
    { name: 'Progressive Party', abbreviation: 'PP' },
  ];

  // Kenyan names for candidates
  private readonly firstNames = [
    'William', 'Raila', 'Musalia', 'Kenyatta', 'Ruto', 'Kalisy', 'Kenyatta',
    'George', 'Uhuru', 'Mwai', 'Jaramogi', 'Odinga', 'Mudavadi', 'Wetangula',
    'Musyoka', 'Kilonzo', 'Mwakazi', 'Njonjo', 'Kosgey', 'Lonyangapuo', 'Wafula',
    'Simeon', 'Kipchumba', 'Murat', 'Abdikadir', 'Hassan', 'Mohammed', 'Ali',
    'Hussein', 'Ahmed', 'Omar', 'Yusuf', 'Ibrahim', 'Saleh', 'Mohamud', 'Abdalla',
    'John', 'Peter', 'James', 'David', 'Michael', 'Samuel', 'Paul', 'Stephen',
    'Joseph', 'Charles', 'Daniel', 'Robert', 'Thomas', 'Andrew', 'Philip', 'Francis'
  ];

  private readonly lastNames = [
    'Kenyatta', 'Odinga', 'Mudavadi', 'Wetangula', 'Ruto', 'Kosgey', 'Wafula',
    'Lonyangapuo', 'Kipchumba', 'Kenyatta', 'Mwai', 'Njonjo', 'Jaramogi', 'Nyamweya',
    'Musyoka', 'Kilonzo', 'Nthenge', 'Wambua', 'Mutua', 'Muthama', 'Ngunjiri',
    'Abdikadir', 'Hassan', 'Mohammed', 'Ali', 'Hussein', 'Omar', 'Yusuf', 'Ibrahim',
    'Saleh', 'Mohamud', 'Abdalla', 'Osman', 'Salad', 'Ahmed', 'Haji', 'Mbarra',
    'Owino', 'Ochieng', 'Omondi', 'Otieno', 'Wafula', 'Wanyama', 'Wekesa', 'Masinde'
  ];

  constructor(
    @InjectRepository(Candidate)
    private readonly candidateRepository: Repository<Candidate>,
    private readonly countySeed: CountySeed,
    private readonly constituencySeed: ConstituencySeed,
    private readonly wardSeed: WardSeed,
    private readonly electionSeed: ElectionSeed,
  ) {}

  private generateDateOfBirth(minAge: number, maxAge: number): Date {
    const today = new Date();
    const year = today.getFullYear() - Math.floor(minAge + Math.random() * (maxAge - minAge));
    const month = Math.floor(Math.random() * 12);
    const day = Math.floor(Math.random() * 28) + 1;
    return new Date(year, month, day);
  }

  private generateCandidateNumber(position: string, index: number): string {
    const prefix = {
      'President': 'P',
      'Governor': 'G',
      'Senator': 'S',
      'MP': 'MP',
      'MCA': 'MCA',
    }[position] || 'C';
    return `${prefix}${index.toString().padStart(3, '0')}`;
  }

  async seed(): Promise<void> {
    this.logger.log('Starting candidate seed...');

    // Get IDs mapping
    const countyIdMap = await this.countySeed.getCountyIds();
    const constituencyIdMap = await this.constituencySeed.getConstituencyIds();
    const wardIdMap = await this.wardSeed.getWardIds();
    const electionIdMap = await this.electionSeed.getElectionIds();

    // Get the general election ID
    const generalElectionId = electionIdMap.get('2024-08-15');

    // Generate Presidential Candidates (5 candidates)
    const presidentialCandidates = await this.generatePresidentialCandidates(countyIdMap, generalElectionId);
    
    // Generate Governor Candidates (10 counties with multiple candidates each)
    const governorCandidates = await this.generateGovernorCandidates(countyIdMap, electionIdMap);
    
    // Generate Senator Candidates (10 counties with multiple candidates each)
    const senatorCandidates = await this.generateSenatorCandidates(countyIdMap, electionIdMap);
    
    // Generate MP Candidates (20 constituencies)
    const mpCandidates = await this.generateMPCandidates(constituencyIdMap, electionIdMap);
    
    // Generate MCA Candidates (20 wards)
    const mcaCandidates = await this.generateMCACandidates(wardIdMap, constituencyIdMap, electionIdMap);

    this.logger.log(`Candidate seed complete.`);
  }

  private async generatePresidentialCandidates(
    countyIdMap: Map<string, string>,
    electionId?: string,
  ): Promise<void> {
    const candidates: CandidateData[] = [
      {
        candidateNumber: 'P001',
        firstName: 'William',
        lastName: 'Ruto',
        middleName: 'Samoei',
        position: 'President',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1961, 10, 20),
        electionId,
      },
      {
        candidateNumber: 'P002',
        firstName: 'Raila',
        lastName: 'Odinga',
        middleName: 'Amolo',
        position: 'President',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1943, 3, 7),
        electionId,
      },
      {
        candidateNumber: 'P003',
        firstName: 'Musalia',
        lastName: 'Mudavadi',
        position: 'President',
        partyName: 'Amani National Congress',
        partyAbbreviation: 'ANC',
        isIndependent: false,
        dateOfBirth: new Date(1961, 3, 21),
        electionId,
      },
      {
        candidateNumber: 'P004',
        firstName: 'George',
        lastName: 'Wajackoyah',
        position: 'President',
        partyName: 'Independent',
        partyAbbreviation: 'IND',
        isIndependent: true,
        dateOfBirth: new Date(1965, 5, 12),
        electionId,
      },
      {
        candidateNumber: 'P005',
        firstName: 'David',
        lastName: 'Waihiga',
        position: 'President',
        partyName: 'Independent',
        partyAbbreviation: 'IND',
        isIndependent: true,
        dateOfBirth: new Date(1970, 8, 30),
        electionId,
      },
    ];

    for (const candidateData of candidates) {
      await this.upsertCandidate(candidateData);
    }
  }

  private async generateGovernorCandidates(
    countyIdMap: Map<string, string>,
    electionIdMap: Map<string, string>,
  ): Promise<void> {
    const governorCandidates: CandidateData[] = [
      // Nairobi County
      {
        candidateNumber: 'G001',
        firstName: 'Johnson',
        lastName: 'Sakaja',
        position: 'Governor',
        countyCode: '001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 6, 9),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G002',
        firstName: 'Anne',
        lastName: 'Kananu',
        position: 'Governor',
        countyCode: '001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 4, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G003',
        firstName: 'Susan',
        lastName: 'Mboya',
        position: 'Governor',
        countyCode: '001',
        partyName: 'Independent',
        partyAbbreviation: 'IND',
        isIndependent: true,
        dateOfBirth: new Date(1975, 8, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Mombasa County
      {
        candidateNumber: 'G004',
        firstName: 'Abdulswamad',
        lastName: 'Shariff',
        position: 'Governor',
        countyCode: '002',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1964, 9, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G005',
        firstName: 'Suleiman',
        lastName: 'Shabhal',
        position: 'Governor',
        countyCode: '002',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1972, 3, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kilifi County
      {
        candidateNumber: 'G006',
        firstName: 'Gideon',
        lastName: 'Mung\'aro',
        position: 'Governor',
        countyCode: '004',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1969, 11, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G007',
        firstName: 'Amason',
        lastName: 'Kingi',
        position: 'Governor',
        countyCode: '004',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 1, 28),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Meru County
      {
        candidateNumber: 'G008',
        firstName: 'Kawira',
        lastName: 'Mwangaza',
        position: 'Governor',
        countyCode: '013',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 7, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G009',
        firstName: 'Kiraitu',
        lastName: 'Murungi',
        position: 'Governor',
        countyCode: '013',
        partyName: 'Agano Party',
        partyAbbreviation: 'AP',
        isIndependent: false,
        dateOfBirth: new Date(1952, 1, 1),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kitui County
      {
        candidateNumber: 'G010',
        firstName: 'Julius',
        lastName: 'Malombe',
        position: 'Governor',
        countyCode: '016',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1967, 3, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G011',
        firstName: 'Charity',
        lastName: 'Ngilu',
        position: 'Governor',
        countyCode: '016',
        partyName: 'National Rainbow Coalition',
        partyAbbreviation: 'NARC',
        isIndependent: false,
        dateOfBirth: new Date(1952, 6, 1),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kiambu County
      {
        candidateNumber: 'G012',
        firstName: 'Kimani',
        lastName: 'Wamatangi',
        position: 'Governor',
        countyCode: '023',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1971, 2, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G013',
        firstName: 'James',
        lastName: 'Nyoro',
        position: 'Governor',
        countyCode: '023',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1965, 9, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Uasin Gishu County
      {
        candidateNumber: 'G014',
        firstName: 'Jonathan',
        lastName: 'Bii',
        position: 'Governor',
        countyCode: '028',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1973, 8, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G015',
        firstName: 'Christopher',
        lastName: 'Aseka',
        position: 'Governor',
        countyCode: '028',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1965, 11, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Nakuru County
      {
        candidateNumber: 'G016',
        firstName: 'Susan',
        lastName: 'Kihika',
        position: 'Governor',
        countyCode: '033',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1974, 12, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G017',
        firstName: 'Lee',
        lastName: 'Kinyanjui',
        position: 'Governor',
        countyCode: '033',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1951, 5, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kakamega County
      {
        candidateNumber: 'G018',
        firstName: 'Wycliffe',
        lastName: 'Oparanya',
        position: 'Governor',
        countyCode: '038',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1961, 1, 1),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G019',
        firstName: 'Fernandes',
        lastName: 'Barasa',
        position: 'Governor',
        countyCode: '038',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1974, 7, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kisumu County
      {
        candidateNumber: 'G020',
        firstName: 'Anyang\'',
        lastName: 'Nyong\'o',
        position: 'Governor',
        countyCode: '043',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1945, 5, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'G021',
        firstName: 'Peter',
        lastName: 'Oduya',
        position: 'Governor',
        countyCode: '043',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1966, 3, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
    ];

    for (const candidateData of governorCandidates) {
      const countyId = countyIdMap.get(candidateData.countyCode!);
      await this.upsertCandidate(candidateData, countyId);
    }
  }

  private async generateSenatorCandidates(
    countyIdMap: Map<string, string>,
    electionIdMap: Map<string, string>,
  ): Promise<void> {
    const senatorCandidates: CandidateData[] = [
      // Nairobi County
      {
        candidateNumber: 'S001',
        firstName: 'Edwin',
        lastName: 'Sifuna',
        position: 'Senator',
        countyCode: '001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1967, 4, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S002',
        firstName: 'Margaret',
        lastName: 'Wanjiru',
        position: 'Senator',
        countyCode: '001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1971, 8, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Mombasa County
      {
        candidateNumber: 'S003',
        firstName: 'Fatuma',
        lastName: 'Achani',
        position: 'Senator',
        countyCode: '002',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1962, 3, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S004',
        firstName: 'Hassan',
        lastName: 'Omar',
        position: 'Senator',
        countyCode: '002',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1962, 11, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kwale County
      {
        candidateNumber: 'S005',
        firstName: 'Boy',
        lastName: 'Juma',
        position: 'Senator',
        countyCode: '003',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 7, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S006',
        firstName: 'Chaurembo',
        lastName: 'Mwamburi',
        position: 'Senator',
        countyCode: '003',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 9, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kilifi County
      {
        candidateNumber: 'S007',
        firstName: 'Stewart',
        lastName: 'Madzayo',
        position: 'Senator',
        countyCode: '004',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1962, 6, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S008',
        firstName: 'Samuel',
        lastName: 'Lombard',
        position: 'Senator',
        countyCode: '004',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1970, 1, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Meru County
      {
        candidateNumber: 'S009',
        firstName: 'Kithure',
        lastName: 'Kindiki',
        position: 'Senator',
        countyCode: '013',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1974, 8, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S010',
        firstName: 'Muthomi',
        lastName: 'Njuki',
        position: 'Senator',
        countyCode: '013',
        partyName: 'Agano Party',
        partyAbbreviation: 'AP',
        isIndependent: false,
        dateOfBirth: new Date(1964, 12, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kitui County
      {
        candidateNumber: 'S011',
        firstName: 'Enock',
        lastName: 'Wambua',
        position: 'Senator',
        countyCode: '016',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1969, 11, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S012',
        firstName: 'Mwinga',
        lastName: 'Mwinga',
        position: 'Senator',
        countyCode: '016',
        partyName: 'National Rainbow Coalition',
        partyAbbreviation: 'NARC',
        isIndependent: false,
        dateOfBirth: new Date(1958, 4, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Machakos County
      {
        candidateNumber: 'S013',
        firstName: 'Victor',
        lastName: 'Kilonzo',
        position: 'Senator',
        countyCode: '017',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1978, 2, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S014',
        firstName: 'Mutua',
        lastName: 'Kilonzo',
        position: 'Senator',
        countyCode: '017',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 6, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Nyeri County
      {
        candidateNumber: 'S015',
        firstName: 'Nahashon',
        lastName: 'Wekesa',
        position: 'Senator',
        countyCode: '020',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1963, 9, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S016',
        firstName: 'Mutahi',
        lastName: 'Kagwe',
        position: 'Senator',
        countyCode: '020',
        partyName: 'The Service Party',
        partyAbbreviation: 'TSP',
        isIndependent: false,
        dateOfBirth: new Date(1958, 6, 21),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kiambu County
      {
        candidateNumber: 'S017',
        firstName: 'Karungo',
        lastName: 'Thang\'wa',
        position: 'Senator',
        countyCode: '023',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1965, 7, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S018',
        firstName: 'James',
        lastName: 'Nyoro',
        position: 'Senator',
        countyCode: '023',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1965, 9, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Nakuru County
      {
        candidateNumber: 'S019',
        firstName: 'Susan',
        lastName: 'Kihika',
        position: 'Senator',
        countyCode: '033',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1974, 12, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'S020',
        firstName: 'Lee',
        lastName: 'Kinyanjui',
        position: 'Senator',
        countyCode: '033',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1951, 5, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
    ];

    for (const candidateData of senatorCandidates) {
      const countyId = countyIdMap.get(candidateData.countyCode!);
      await this.upsertCandidate(candidateData, countyId);
    }
  }

  private async generateMPCandidates(
    constituencyIdMap: Map<string, string>,
    electionIdMap: Map<string, string>,
  ): Promise<void> {
    const mpCandidates: CandidateData[] = [
      // Westlands Constituency (Nairobi)
      {
        candidateNumber: 'MP001',
        firstName: 'Tim',
        lastName: 'Wanyonyi',
        position: 'MP',
        constituencyCode: '001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1973, 5, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP002',
        firstName: 'Judy',
        lastName: 'Wakhungu',
        position: 'MP',
        constituencyCode: '001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 9, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Langata Constituency (Nairobi)
      {
        candidateNumber: 'MP003',
        firstName: 'Felix',
        lastName: 'Odiwuor',
        position: 'MP',
        constituencyCode: '006',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1978, 3, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP004',
        firstName: 'Margaret',
        lastName: 'Wanjiru',
        position: 'MP',
        constituencyCode: '006',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1971, 8, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kisauni Constituency (Mombasa)
      {
        candidateNumber: 'MP005',
        firstName: 'Ali',
        lastName: 'Mbogo',
        position: 'MP',
        constituencyCode: '018',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1962, 7, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP006',
        firstName: 'Mishi',
        lastName: 'Mboko',
        position: 'MP',
        constituencyCode: '018',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 11, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Msambweni Constituency (Kwale)
      {
        candidateNumber: 'MP007',
        firstName: 'Willis',
        lastName: 'Sambo',
        position: 'MP',
        constituencyCode: '024',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1963, 4, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP008',
        firstName: 'Feisal',
        lastName: 'Bader',
        position: 'MP',
        constituencyCode: '024',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1970, 8, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kilifi North Constituency
      {
        candidateNumber: 'MP009',
        firstName: 'Owen',
        lastName: 'Baya',
        position: 'MP',
        constituencyCode: '028',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1977, 12, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP010',
        firstName: 'Mohamed',
        lastName: 'Twaha',
        position: 'MP',
        constituencyCode: '028',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1968, 6, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // North Imenti Constituency (Meru)
      {
        candidateNumber: 'MP011',
        firstName: 'Rahim',
        lastName: 'Dawood',
        position: 'MP',
        constituencyCode: '067',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1963, 9, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP012',
        firstName: 'Moses',
        lastName: 'Kirima',
        position: 'MP',
        constituencyCode: '067',
        partyName: 'Agano Party',
        partyAbbreviation: 'AP',
        isIndependent: false,
        dateOfBirth: new Date(1978, 2, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Mwingi Central Constituency (Kitui)
      {
        candidateNumber: 'MP013',
        firstName: 'Charles',
        lastName: 'Nguna',
        position: 'MP',
        constituencyCode: '083',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 11, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP014',
        firstName: 'Munyasya',
        lastName: 'Waweru',
        position: 'MP',
        constituencyCode: '083',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1972, 7, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Yatta Constituency (Machakos)
      {
        candidateNumber: 'MP015',
        firstName: 'Robert',
        lastName: 'Mbui',
        position: 'MP',
        constituencyCode: '091',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1976, 4, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP016',
        firstName: 'John',
        lastName: 'Mulei',
        position: 'MP',
        constituencyCode: '091',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1969, 1, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kieni Constituency (Nyeri)
      {
        candidateNumber: 'MP017',
        firstName: 'Japhet',
        lastName: 'Mbiuki',
        position: 'MP',
        constituencyCode: '112',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1978, 6, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP018',
        firstName: 'John',
        lastName: 'Kihagi',
        position: 'MP',
        constituencyCode: '112',
        partyName: 'The Service Party',
        partyAbbreviation: 'TSP',
        isIndependent: false,
        dateOfBirth: new Date(1961, 3, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Gatundu South Constituency (Kiambu)
      {
        candidateNumber: 'MP019',
        firstName: 'Moses',
        lastName: 'Kuria',
        position: 'MP',
        constituencyCode: '130',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1971, 11, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP020',
        firstName: 'Joseph',
        lastName: 'Karinga',
        position: 'MP',
        constituencyCode: '130',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1965, 9, 28),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Rongai Constituency (Nakuru)
      {
        candidateNumber: 'MP021',
        firstName: 'Linus',
        lastName: 'Kipkorir',
        position: 'MP',
        constituencyCode: '142',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 8, 10),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP022',
        firstName: 'Daniel',
        lastName: 'Koech',
        position: 'MP',
        constituencyCode: '142',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1972, 12, 3),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Ainamoi Constituency (Kericho)
      {
        candidateNumber: 'MP023',
        firstName: 'Benjamin',
        lastName: 'Langat',
        position: 'MP',
        constituencyCode: '160',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1978, 4, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP024',
        firstName: 'Samson',
        lastName: 'Kiprotich',
        position: 'MP',
        constituencyCode: '160',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1969, 7, 17),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Belgut Constituency (Kericho)
      {
        candidateNumber: 'MP025',
        firstName: 'Nelson',
        lastName: 'Koech',
        position: 'MP',
        constituencyCode: '185',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 2, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP026',
        firstName: 'Charles',
        lastName: 'Keter',
        position: 'MP',
        constituencyCode: '185',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 10, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Hamisi Constituency (Vihiga)
      {
        candidateNumber: 'MP027',
        firstName: 'Chris',
        lastName: 'Wamalwa',
        position: 'MP',
        constituencyCode: '218',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1971, 6, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP028',
        firstName: 'Wilberforce',
        lastName: 'Oundo',
        position: 'MP',
        constituencyCode: '218',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1974, 9, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Matungu Constituency (Kakamega)
      {
        candidateNumber: 'MP029',
        firstName: 'Justus',
        lastName: 'Kizito',
        position: 'MP',
        constituencyCode: '235',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1963, 12, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP030',
        firstName: 'Fredrick',
        lastName: 'Outa',
        position: 'MP',
        constituencyCode: '235',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1977, 5, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Muhoroni Constituency (Kisumu)
      {
        candidateNumber: 'MP031',
        firstName: 'James',
        lastName: 'Opiyo',
        position: 'MP',
        constituencyCode: '251',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1966, 8, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP032',
        firstName: 'Ochieng',
        lastName: 'Adala',
        position: 'MP',
        constituencyCode: '251',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1970, 11, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Nyakach Constituency (Kisumu)
      {
        candidateNumber: 'MP033',
        firstName: 'Pius',
        lastName: 'Okwach',
        position: 'MP',
        constituencyCode: '257',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1974, 3, 28),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP034',
        firstName: 'Miguna',
        lastName: 'Miguna',
        position: 'MP',
        constituencyCode: '257',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1962, 12, 6),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Seme Constituency (Kisumu)
      {
        candidateNumber: 'MP035',
        firstName: 'James',
        lastName: 'Agina',
        position: 'MP',
        constituencyCode: '264',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1968, 1, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP036',
        firstName: 'Washington',
        lastName: 'Jakoyo',
        position: 'MP',
        constituencyCode: '264',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 7, 19),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Eldoret East Constituency (Uasin Gishu)
      {
        candidateNumber: 'MP037',
        firstName: 'William',
        lastName: 'Chelangat',
        position: 'MP',
        constituencyCode: '278',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1976, 9, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP038',
        firstName: 'Benjamin',
        lastName: 'Washiali',
        position: 'MP',
        constituencyCode: '278',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1969, 4, 7),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Soy Constituency (Uasin Gishu)
      {
        candidateNumber: 'MP039',
        firstName: 'David',
        lastName: 'Kiptanui',
        position: 'MP',
        constituencyCode: '287',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1971, 12, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MP040',
        firstName: 'Collins',
        lastName: ' Injera',
        position: 'MP',
        constituencyCode: '287',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1964, 8, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
    ];

    for (const candidateData of mpCandidates) {
      const constituencyId = constituencyIdMap.get(candidateData.constituencyCode!);
      await this.upsertCandidate(candidateData, undefined, constituencyId);
    }
  }

  private async generateMCACandidates(
    wardIdMap: Map<string, string>,
    constituencyIdMap: Map<string, string>,
    electionIdMap: Map<string, string>,
  ): Promise<void> {
    const mcaCandidates: CandidateData[] = [
      // Westlands Ward (Westlands Constituency, Nairobi)
      {
        candidateNumber: 'MCA001',
        firstName: 'John',
        lastName: 'Kamau',
        position: 'MCA',
        constituencyCode: '001',
        wardCode: '001001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1980, 3, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA002',
        firstName: 'Mary',
        lastName: 'Wanjiku',
        position: 'MCA',
        constituencyCode: '001',
        wardCode: '001001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1978, 7, 22),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Parklands Ward (Westlands Constituency, Nairobi)
      {
        candidateNumber: 'MCA003',
        firstName: 'David',
        lastName: 'Ochieng',
        position: 'MCA',
        constituencyCode: '001',
        wardCode: '001006',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 11, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA004',
        firstName: 'Grace',
        lastName: 'Achieng',
        position: 'MCA',
        constituencyCode: '001',
        wardCode: '001006',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1982, 1, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Koinange Ward (Starehe Constituency, Nairobi)
      {
        candidateNumber: 'MCA005',
        firstName: 'Peter',
        lastName: 'Mwangi',
        position: 'MCA',
        constituencyCode: '002',
        wardCode: '001021',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 6, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA006',
        firstName: 'Sarah',
        lastName: 'Njeri',
        position: 'MCA',
        constituencyCode: '002',
        wardCode: '001021',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1981, 9, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kisauni Ward (Kisauni Constituency, Mombasa)
      {
        candidateNumber: 'MCA007',
        firstName: 'Ahmed',
        lastName: 'Hassan',
        position: 'MCA',
        constituencyCode: '018',
        wardCode: '002002',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1976, 4, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA008',
        firstName: 'Fatuma',
        lastName: 'Ali',
        position: 'MCA',
        constituencyCode: '018',
        wardCode: '002002',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1983, 12, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Msambweni Ward (Msambweni Constituency, Kwale)
      {
        candidateNumber: 'MCA009',
        firstName: 'Juma',
        lastName: 'Kombo',
        position: 'MCA',
        constituencyCode: '024',
        wardCode: '003001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1974, 8, 25),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA010',
        firstName: 'Asha',
        lastName: 'Said',
        position: 'MCA',
        constituencyCode: '024',
        wardCode: '003001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1980, 2, 7),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Tezo Ward (Kilifi North Constituency, Kilifi)
      {
        candidateNumber: 'MCA011',
        firstName: 'Mzee',
        lastName: 'Chizi',
        position: 'MCA',
        constituencyCode: '028',
        wardCode: '004001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1965, 11, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA012',
        firstName: 'Salma',
        lastName: 'Mohamed',
        position: 'MCA',
        constituencyCode: '028',
        wardCode: '004001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1978, 5, 3),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Abogeta East Ward (North Imenti Constituency, Meru)
      {
        candidateNumber: 'MCA013',
        firstName: 'Jackson',
        lastName: 'Kilonzo',
        position: 'MCA',
        constituencyCode: '067',
        wardCode: '013001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1977, 10, 15),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA014',
        firstName: 'Rose',
        lastName: 'Muthoni',
        position: 'MCA',
        constituencyCode: '067',
        wardCode: '013001',
        partyName: 'Agano Party',
        partyAbbreviation: 'AP',
        isIndependent: false,
        dateOfBirth: new Date(1982, 3, 28),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kyuso Ward (Mwingi Central Constituency, Kitui)
      {
        candidateNumber: 'MCA015',
        firstName: 'Mutua',
        lastName: 'Musyoka',
        position: 'MCA',
        constituencyCode: '083',
        wardCode: '016004',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1979, 7, 9),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA016',
        firstName: 'Catherine',
        lastName: 'Ndinda',
        position: 'MCA',
        constituencyCode: '083',
        wardCode: '016004',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1981, 12, 1),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kithimani Ward (Yatta Constituency, Machakos)
      {
        candidateNumber: 'MCA017',
        firstName: 'Joseph',
        lastName: 'Musyoki',
        position: 'MCA',
        constituencyCode: '091',
        wardCode: '017003',
        partyName: 'Wiper Democratic Movement',
        partyAbbreviation: 'WDM',
        isIndependent: false,
        dateOfBirth: new Date(1976, 1, 17),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA018',
        firstName: 'Ann',
        lastName: 'Wambui',
        position: 'MCA',
        constituencyCode: '091',
        wardCode: '017003',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1984, 6, 24),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Naromoru Ward (Kieni Constituency, Nyeri)
      {
        candidateNumber: 'MCA019',
        firstName: 'Samuel',
        lastName: 'Gachanja',
        position: 'MCA',
        constituencyCode: '112',
        wardCode: '020003',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1978, 9, 11),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA020',
        firstName: 'Lucy',
        lastName: 'Wairimu',
        position: 'MCA',
        constituencyCode: '112',
        wardCode: '020003',
        partyName: 'The Service Party',
        partyAbbreviation: 'TSP',
        isIndependent: false,
        dateOfBirth: new Date(1983, 4, 6),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kiamwangi Ward (Gatundu South Constituency, Kiambu)
      {
        candidateNumber: 'MCA021',
        firstName: 'Peter',
        lastName: 'Njuguna',
        position: 'MCA',
        constituencyCode: '130',
        wardCode: '023001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1975, 8, 19),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA022',
        firstName: 'Grace',
        lastName: 'Wanjiku',
        position: 'MCA',
        constituencyCode: '130',
        wardCode: '023001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1980, 11, 13),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Menengai Ward (Nakuru Town West Constituency, Nakuru)
      {
        candidateNumber: 'MCA023',
        firstName: 'James',
        lastName: 'Kiprop',
        position: 'MCA',
        constituencyCode: '142',
        wardCode: '033001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1977, 2, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA024',
        firstName: 'Beatrice',
        lastName: 'Chebet',
        position: 'MCA',
        constituencyCode: '142',
        wardCode: '033001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1982, 7, 21),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kapkateny Ward (Ainamoi Constituency, Kericho)
      {
        candidateNumber: 'MCA025',
        firstName: 'Paul',
        lastName: 'Kiprop',
        position: 'MCA',
        constituencyCode: '160',
        wardCode: '027001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1979, 5, 4),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA026',
        firstName: 'Rose',
        lastName: 'Chepkorir',
        position: 'MCA',
        constituencyCode: '160',
        wardCode: '027001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1981, 10, 16),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kabianga Ward (Belgut Constituency, Kericho)
      {
        candidateNumber: 'MCA027',
        firstName: 'Simon',
        lastName: 'Kiprop',
        position: 'MCA',
        constituencyCode: '185',
        wardCode: '028001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1976, 12, 29),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA028',
        firstName: 'Janet',
        lastName: 'Chepkoech',
        position: 'MCA',
        constituencyCode: '185',
        wardCode: '028001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1984, 3, 9),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Shiru Ward (Hamisi Constituency, Vihiga)
      {
        candidateNumber: 'MCA029',
        firstName: 'Michael',
        lastName: 'Mukhwana',
        position: 'MCA',
        constituencyCode: '218',
        wardCode: '038001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1978, 6, 7),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA030',
        firstName: 'Susan',
        lastName: 'Makhoha',
        position: 'MCA',
        constituencyCode: '218',
        wardCode: '038001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1983, 1, 23),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Koyonzo Ward (Matungu Constituency, Kakamega)
      {
        candidateNumber: 'MCA031',
        firstName: 'Francis',
        lastName: 'Atwoli',
        position: 'MCA',
        constituencyCode: '235',
        wardCode: '040001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1955, 8, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA032',
        firstName: 'Mercy',
        lastName: 'Nambuye',
        position: 'MCA',
        constituencyCode: '235',
        wardCode: '040001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1980, 9, 30),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Chemelil Ward (Muhoroni Constituency, Kisumu)
      {
        candidateNumber: 'MCA033',
        firstName: 'Tom',
        lastName: 'Oduya',
        position: 'MCA',
        constituencyCode: '251',
        wardCode: '042001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1974, 11, 2),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA034',
        firstName: 'Ann',
        lastName: 'Oduya',
        position: 'MCA',
        constituencyCode: '251',
        wardCode: '042001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1982, 5, 18),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kobura Ward (Nyakach Constituency, Kisumu)
      {
        candidateNumber: 'MCA035',
        firstName: 'George',
        lastName: 'Oduya',
        position: 'MCA',
        constituencyCode: '257',
        wardCode: '043001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1977, 4, 12),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA036',
        firstName: 'Mary',
        lastName: 'Achieng',
        position: 'MCA',
        constituencyCode: '257',
        wardCode: '043001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1985, 8, 27),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Usenge Ward (Seme Constituency, Kisumu)
      {
        candidateNumber: 'MCA037',
        firstName: 'Paul',
        lastName: 'Ondiek',
        position: 'MCA',
        constituencyCode: '264',
        wardCode: '044001',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1979, 7, 5),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA038',
        firstName: 'Rose',
        lastName: 'Akinyi',
        position: 'MCA',
        constituencyCode: '264',
        wardCode: '044001',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1981, 12, 14),
        electionId: electionIdMap.get('2024-08-15'),
      },
      // Kimumu Ward (Eldoret East Constituency, Uasin Gishu)
      {
        candidateNumber: 'MCA039',
        firstName: 'David',
        lastName: 'Koech',
        position: 'MCA',
        constituencyCode: '278',
        wardCode: '046004',
        partyName: 'United Democratic Alliance',
        partyAbbreviation: 'UDA',
        isIndependent: false,
        dateOfBirth: new Date(1978, 10, 20),
        electionId: electionIdMap.get('2024-08-15'),
      },
      {
        candidateNumber: 'MCA040',
        firstName: 'Grace',
        lastName: 'Chebet',
        position: 'MCA',
        constituencyCode: '278',
        wardCode: '046004',
        partyName: 'Orange Democratic Movement',
        partyAbbreviation: 'ODM',
        isIndependent: false,
        dateOfBirth: new Date(1983, 3, 8),
        electionId: electionIdMap.get('2024-08-15'),
      },
    ];

    for (const candidateData of mcaCandidates) {
      const constituencyId = constituencyIdMap.get(candidateData.constituencyCode!);
      const wardId = wardIdMap.get(candidateData.wardCode!);
      await this.upsertCandidate(candidateData, undefined, constituencyId, wardId);
    }
  }

  private async upsertCandidate(
    candidateData: CandidateData,
    countyId?: string,
    constituencyId?: string,
    wardId?: string,
  ): Promise<void> {
    try {
      const existing = await this.candidateRepository.findOne({
        where: { candidateNumber: candidateData.candidateNumber },
      });

      if (existing) {
        await this.candidateRepository.update(existing.id, {
          firstName: candidateData.firstName,
          lastName: candidateData.lastName,
          middleName: candidateData.middleName,
          position: candidateData.position,
          countyId,
          constituencyId,
          wardId,
          partyName: candidateData.partyName,
          partyAbbreviation: candidateData.partyAbbreviation,
          isIndependent: candidateData.isIndependent,
          dateOfBirth: candidateData.dateOfBirth,
          electionId: candidateData.electionId,
          status: 'approved',
          approvedAt: new Date(),
        });
      } else {
        const candidate = this.candidateRepository.create({
          candidateNumber: candidateData.candidateNumber,
          firstName: candidateData.firstName,
          lastName: candidateData.lastName,
          middleName: candidateData.middleName,
          position: candidateData.position,
          countyId,
          constituencyId,
          wardId,
          partyName: candidateData.partyName,
          partyAbbreviation: candidateData.partyAbbreviation,
          isIndependent: candidateData.isIndependent,
          dateOfBirth: candidateData.dateOfBirth,
          electionId: candidateData.electionId,
          status: 'approved',
          submittedAt: new Date(),
          approvedAt: new Date(),
        });
        await this.candidateRepository.save(candidate);
      }
    } catch (error) {
      this.logger.error(`Error upserting candidate ${candidateData.candidateNumber}:`, error.message);
    }
  }
}
